### ISSUE TITLE
Add activity type for recruitments...on travel Request and reimb forms

### ISSUE THREAD

**Issue by dgallardo** [ucb-las/las-project#108]
- Add "Recruitment KOTR06" under "Activity Type"  -- make this only available to HR Analysts, LBS Analyst, AULs, ULs
- Add "Recruitment" amount field under "To Be Paid By" -- only visible to HR Analysts, LBS Analyst, AULs, ULs
- update Reimbursement form fields as needed...

**Comment by kcleonardo** [comment]
no need to restrict by role
