### ISSUE TITLE
Add validation check on the pre-approval request form to ensure that the total estimated expense amount is accounted for in the funding distribution section.

### ISSUE THREAD

**Issue by dgallardo** [ucb-las/las-project#128]
estimated totals should match actual totals (disbursements) on travel preapproval form

**Comment by dgallardo** [comment]
- Change field group title to "Funding Distribution"
- add field to "TO Be PAID BY" - Total  Funding
- add help text under "To be paid By" - "Please indicate how your expenses will be funded. The total estimated expense amount must match total funding  amount."
- change label Traveler/Requestor/Out of Pocket...label to "Traveler/Requestor"  
- show error message - "Total estimated expense amount does not match total funding amount. Please account for all expenses."
- don't allow the person to Save form if these amounts don't match

**Comment by kcleonardo** [comment]
- move "Funding Distribution Total" to bottom of Funding Distribution group
- highlight "Funding Distribution Total" instead of individual funding sources.
- change to inline sentences (see Desi's notes)

**Comment by kcleonardo** [comment]
still to do: highlight "Funding Distribution Total" instead of individual funding sources.

**Comment by kcleonardo** [comment]
highlight "total estimated expenses" also
