### ISSUE TITLE
Update training materials for travel request and reimbursement

### ISSUE THREAD

**Issue by dgallardo** [ucb-las/las-project#129]

**Comment by dgallardo** [comment]
awaiting Honza's changes

**Comment by kcleonardo** [comment]
add new travel approval delegation view in training guide for auls/directors

**Comment by dtruppi** [comment]
replacing guides with LBS travel page

**Comment by kcleonardo** [comment]
Honza, please replace the guides with a link to the LBS travel page: http://www.lib.berkeley.edu/Staff/LBS/travel.html.

**Comment by kcleonardo** [comment]
Remove submenus from Help->Travel.
On the dashboard, Staff Resources section, change "Travel Request and Approval" to "Travel" and change "LBS Travel Page" to "Travel Policy and Procedures".
