### ISSUE TITLE
Deal with restricted info fields

### ISSUE THREAD

**Issue by dgallardo** [ucb-las/las-project#130]
- mailing address in travel request and reimbursement forms
- pull work phone and email from request form into reimbursement form

**Comment by kcleonardo** [comment]
To do: pull work phone and email from request form into reimbursement form

**Comment by kcleonardo** [comment]
Error messagePDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'node-1121-0-0-und' for key 'PRIMARY': INSERT INTO {field_data_field_total_estimated_expense} (entity_type, entity_id, revision_id, bundle, delta, language, field_total_estimated_expense_value) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4, :db_insert_placeholder_5, :db_insert_placeholder_6); Array ( [:db_insert_placeholder_0] => node [:db_insert_placeholder_1] => 1121 [:db_insert_placeholder_2] => 1688 [:db_insert_placeholder_3] => travel_form [:db_insert_placeholder_4] => 0 [:db_insert_placeholder_5] => und [:db_insert_placeholder_6] => 0 ) in field_sql_storage_field_storage_write()
The website encountered an unexpected error. Please try again later.

**Comment by honzi** [comment]
Error caused when going draft -> approved. Won't happen normally but still should fix.
