### ISSUE TITLE
#1 priority - fix travel approval buttons based on what we found out when we tested it at 17:11

### ISSUE THREAD

**Issue by dgallardo** [ucb-las/las-project#139]

**Comment by kcleonardo** [comment]
show error message if traveler edits requests when it's not in draft or requires revision

**Comment by kcleonardo** [comment]
still to do:  revise error message to include email address of next approver and let traveler know that they would need to ask the next approver to click requires revision.

**Comment by kcleonardo** [comment]
author's can't create new requests

**Comment by kcleonardo** [comment]
creating new issue for "revise error message to include email address of next approver and let traveler know that they would need to ask the next approver to click requires revision."
