### ISSUE TITLE
Add fields under Administrative and Collections Development Funding Distribution

### ISSUE THREAD

**Issue by kcleonardo** [ucb-las/las-project#158]
If using a special unit chartstring, please specify it here: ____

**Comment by kcleonardo** [comment]
Conditional field... if dollar amount is greater than zero, display new field

**Comment by honzi** [comment]
add conditional description to administrative and collection dev fields

**Comment by kcleonardo** [comment]
Change field title to "If using a special chartstring, please specify it below:"
Also, indent the field.
For Description of Other Funding, display only if amount entered in Other is not zero.  Indent the Description of Other Funding field.
