### ISSUE TITLE
fix travel approval and travel reimbursement views

### ISSUE THREAD

**Issue by honzi** [ucb-las/las-project#20]

**Comment by dgallardo** [comment]
"Travel Approval" tab - AULs and LBS analysts should be able to view all requests at all stages/states. so is it also possible to enable filters? (filter by traveler, AUL, state, activity type)

**Comment by dgallardo** [comment]
what do supervisors and department heads see in their tab? - work with Tyler

**Comment by dgallardo** [comment]
LBS Analyst needs to be able to view all completed Travel Requests and Reimbursements , with filter and sort

**Comment by dgallardo** [comment]
Traveler needs a tab to view reimbursement request forms ("My Travel Reimbursements")
