### ISSUE TITLE
Make finding the travel reimbursement form more intuitive

### ISSUE THREAD

**Issue by kcleonardo** [ucb-las/las-project#201]
For example, add a travel menu in the toolbar, add a link to the reimbursement form on the request form.

**Comment by kcleonardo** [comment]
ask Desi for her opinion.. she might want to add a student req menu

**Comment by dgallardo** [comment]
Student Employment

**Comment by dgallardo** [comment]
(Some items are renamed, so the old names are in parens)

Student Employment
  --My Student Jobs (My Job Requests)
  --All Student Jobs (Manage all jobs)
  --Jobs Pending HR Approval (Manage Requested Jobs)
  --Jobs Pending LBS Approval (LBS Worklist)
  --Jobs Approved by LBS (Approved by LBS)
  --Student Hire Requests (Manage Hire Requests)
Travel and Entertainment
  --(defer to Kris and Danielle's direction)
Admin
  --Users (Manage Users)
  --Units and Departments (Library Units)
  --Chartstrings and Friendly Names (Manage Chartstrings)
  --Broken Reimbursement Finder
  --Broken Travel Request Finder
