### ISSUE TITLE
change order of buttons in node edit and workflow

### ISSUE THREAD

**Issue by kcleonardo** [ucb-las/las-project#218]
save as draft
preview
view changes
request ___ approval

**Comment by kcleonardo** [comment]
theme the buttons

**Comment by dgallardo** [comment]
Supervisor, Dept Head: Save Changes without Approving, Return to Requestor, Decline, Approve
AUL: Save Changes without Approving, Return to Requestor, Decline, Approve and Submit to SDC, Approve and Submit to Collection Development Approver, Approve and Submit to UL, Approve and Submit to LBS

**Comment by dgallardo** [comment]
UL: Save Changes without Approving, Return to Requestor, Approve and Submit to Collection Development Approver, Approve and Submit to LBS .... **Does UL need to have access to Decline button?**

**Comment by kcleonardo** [comment]
Yes, I think the UL should have access to the Decline button.  Honza, can you please insert the Decline button before the approval buttons?  Thanks.

**Comment by kcleonardo** [comment]
The order of the buttons seems to have changed.  Please check and reorder.

**Comment by honzi** [comment]
This can be solved by saving the configuration for the workflow field on the travel_form. Figure out a way to do this with PHP!

**Comment by kcleonardo** [comment]
SDC Chair: Save Changes without Approving, Return to Requestor, Decline, Approve and Submit to AUL, Approve and Submit to LBS
Collections AUL: Save Changes without Approving, Return to Requestor, Decline, Approve
UL: Save Changes without Approving, Return to Requestor, Decline, Approve and Submit to Collection Development Approver, Approve and Submit to LBS
