### ISSUE TITLE
for drivers license verification, if unchecked, display "n/a" in node view and hide expiration date (delete if necessary). if checked, display "validated" and expiration date

### ISSUE THREAD

**Issue by kcleonardo** [ucb-las/las-project#232]

**Comment by honzi** [comment]
hi

**Comment by kcleonardo** [comment]
Instead of the change mentioned in the title, change the label for the checkbox to "Check this box if you are driving on University business."
Keep the rest of the statement, "By providing your..."
If the box is unchecked, hide it in node view just how it is now.
If the box is checked, show the statement just how it is now.  But in node view, show the following:
"Driving on University business? Yes"
