### ISSUE TITLE
Add help text for Comments field in Travel Pre-approval and Expense Report

### ISSUE THREAD

**Issue by kcleonardo** [ucb-las/las-project#258]
for author and non-authors

**Comment by dtruppi** [comment]
In the "Form Help Text" doc in the shared drive, pg. 5-6

**Comment by kcleonardo** [comment]
I've reviewed Danielle's draft.  I'm assigning this to Honza for implementation.

**Comment by kcleonardo** [comment]
Add help text for Comments in Travel Pre-Approval's approvals tab for author role.
Add help text for Comments in Travel Expense Report's node edit and approvals tab for author role.
