### ISSUE TITLE
Add Data Privacy instructions in Instructions under Node Edit of Travel Pre-approval and Travel Expense Report

### ISSUE THREAD

**Issue by kcleonardo** [ucb-las/las-project#271]
Use Data Privacy instructions from BearBuy's payment request form as a guide.

**Comment by dtruppi** [comment]
Added instructions for what not to include in uploaded documentation in "Form Help Text" doc.

**Comment by kcleonardo** [comment]
I've reviewed Danielle's draft.  I'm assigning this to Honza for implementation.
