### ISSUE TITLE
add withdrawn state to travel pre-approval

### ISSUE THREAD

**Issue by honzi** [ucb-las/las-project#286]

**Comment by kcleonardo** [comment]
Canceled state might be better because people might get confused between Withdraw and Return to Draft.

**Comment by kcleonardo** [comment]
According to Lynne, "It is complex to cancel a request in the midst of a workflow. We propose that for now all cancels be handled by LAS via the backend. LAS is able to “unpublish”. We could verify the complexity of the change if you outline how you see this working and when users would be offered a cancel option."  This is low on our priority list, so we'll cancel this request.
