### ISSUE TITLE
$ sign in travel expense report

### ISSUE THREAD

**Issue by richardtrann** [ucb-las/las-project#309]
In the node view of the travel expense report, add a default $ sign for the amount field of the COA table

**Comment by honzi** [comment]
Wasn't the COA table removed during recent optimizations?

**Comment by kcleonardo** [comment]
We are referring to the table where we enter the chartstring values: account, fund, dept id, etc.  The entries for this table do not get saved.  It would be nice to have a $ sign in the field where we enter the amount.  If there isn't a quick solution, let's move this to sprint 3.  Thanks.
