### ISSUE TITLE
Add auto-sum calculations to reimbursement form

### ISSUE THREAD

**Issue by dgallardo** [ucb-las/las-project#31]

**Comment by dgallardo** [comment]
running totals should be visible above the Chart of Accounts field/table:
Subtotal 1 = Airfare
Subtotal 2 = non-Airfare (all ground, rental car, non-airfare trans, meals, hotels, "Other expenses" field
Subtotal 3 = Conference/registration fees

**Comment by honzi** [comment]
airfare depends on direct bill
registration depends on blu card
