### ISSUE TITLE
Conditional Rule for Librarian under Registration Expenses

### ISSUE THREAD

**Issue by richardtrann** [ucb-las/las-project#324]
When a user selects and inputs a numerical value for registration, there will be a question asking if the user is a librarian or not. 

If the user is a Librarian, their will be a content field asking if they are applying their funds to a conference/event or for membership fees. 

If user is not a Librarian, keep the status quo.

**Comment by honzi** [comment]
Copy registration field format and show the fields/calculations to librarians, AULs, and LBS.

**Comment by kcleonardo** [comment]
Travel Pre-approval:
Field label: Membership
Tooltip: The Library may pay for institutional memberships in organizations, other than social organizations, if a genuine business purpose can be established.  Requests for individual or personal membership may only be submitted by Librarians with LAUC-B funding.
Field type: dollar
Travel Pre-approval Request Conditional field label: Would you like to directly bill the membership dues to UCB? \* (required field, default to No)
Conditional Boolean field answers: No Yes

Travel Expense Report:
Estimated Membership Total: (prepopulated from Travel Pre-approval)
Field label: Actual Membership Dues
Tooltip: The Library may pay for institutional memberships in organizations, other than social organizations, if a genuine business purpose can be established.  Requests for individual or personal membership may only be submitted by Librarians with LAUC-B funding.
Field type: dollar
Travel Expense Report Conditional field label: Were the membership dues directly billed to UCB (e.g. charged on Blucard)? \*  (required field, default to No)
Travel Expense Report Conditional field help text: Select 'No' if you paid for the membership dues personally (out of pocket.)
Conditional Boolean field answers: No Yes

**Comment by kcleonardo** [comment]
If requestor is a non-librarian and the approver is a librarian, hide the membership direct bill question and the membership in the expense summary table from the approver.

**Comment by kcleonardo** [comment]
Hide estimated membership field and direct bill question in the Expense report.  Show actual membership amount and direct bill question when amount is entered in actual membership field.

**Comment by kcleonardo** [comment]
Use the actual membership amount in the calculation script for the Summary of Expenses table.

**Comment by kcleonardo** [comment]
Change order of expense categories in Summary of Estimated Expenses table of Travel Pre-approval Request Form to match the order of expense categories in the Estimated Expenses: Registration, Membership, Airfare, etc.

**Comment by kcleonardo** [comment]
In My Travel Pre-approval Request view and My Travel Expense Reports view, Travel Approval view, the Total Estimated Expense amount should include the estimated Membership amount.

**Comment by kcleonardo** [comment]
Order of expense categories should be:
Airfare
Registration
Membership (display if author is a librarian)
Non-airfare     
- Personal Car
- Rental Car
- Other Ground Transportation
- Other Expenses
- Lodging
- M&IE Actuals
