### ISSUE TITLE
update 2016 Standard Mileage Rates for Business

### ISSUE THREAD

**Issue by richardtrann** [ucb-las/las-project#329]
Revise the standard mileage rates for the use of a car for business to 54 cents per mile for business miles driven, down from 57.5 cents for 2015

https://www.irs.gov/uac/Newsroom/2016-Standard-Mileage-Rates-for-Business-Medical-and-Moving-Announced

**Comment by richardtrann** [comment]
see #188 - we need a dropdown selection for mileage rates based on year

**Comment by richardtrann** [comment]
Also FYI, the reimbursement rate for driving an automobile in connection with a move or relocation has decreased from 23 cents a mile to 19 cents a mile.

**Comment by kcleonardo** [comment]
Bug: When mileage is entered, then saved to draft, the edit view does not remember the previously entered mileage.

**Comment by kcleonardo** [comment]
bug has been fixed
