### ISSUE TITLE
Test: Navigation (menus, breadcrumbs)

### ISSUE THREAD

**Issue by dgallardo** [ucb-las/las-project#352]
Examples of things to test:
- Are menu items linking to the correct pages? 
- Are there dead links? 
- Breadcrumbs leading back to the right place based on the url?
- Is search function pulling up all types of content? Are filters working?
- Is the form repo (view) working? Are filters working? Are columns able to be sorted?
- On general info pages, are related resources and related topics showing up?

**Comment by kcleonardo** [comment]
- [x] incomplete breadcrumbs for http://test-lhrdredesign.pantheon.berkeley.edu/lbs/overview-of-procedures-for-funding-approval-requests 
- [x] ~~highlight or bold the item on the left menu whose content is displayed~~
- [x] the filters on the right side of the search results don't seem to work for travel
- [x] on the search results can we echo what we searched for, e.g., if i search for travel, can we display "search results for travel"
- [x] ~~when i click on search or content on the breadcrumbs for search results, it gives a blank page.~~

**Comment by dgallardo** [comment]
- [x] ~~lhrd has missing menu items in the left side menu bar~~
- [x] ~~@honzi how do i create the secondary navigation supermenus?~~
- [x] ~~some footer menu links missing~~
- [x] ~~can the lhrd breadcrumbs contain the section (e.g. staff, academic, etc) and if the page is part of a book, then contain the name of the book? (e.g. Home >> Library Human Resources >> Guides and Manuals >> Volunteer Handbook >> About the Library for http://test-lhrdredesign.pantheon.berkeley.edu/lhrd/manuals/volunteer-handbook/about-the-library)~~
- [x] ~~display related topics in a comma separated block of text~~

**Comment by dgallardo** [comment]
- [x] ~~capitalize "LHRD" in breadcrumbs...might go the same for other LAS units~~

**Comment by dgallardo** [comment]
Search results
- [ ] for public users, only show General Information, LAS job, Student Job, Contact, FAQ results.
- [ ] filters should be: LAS unit (label: "Department"), Content Type (label: "Type")

**Comment by dgallardo** [comment]
Forms (/forms)

- [ ] see mockup ("forms repo")
- [ ] view should contain items where Resource type = Form

**Comment by dgallardo** [comment]
once @kcleonardo reviews what @honzi has checked off, then I'll close this issue.
