### ISSUE TITLE
Stuff Honza Needs

### ISSUE THREAD

**Issue by honzi** [ucb-las/las-project#362]
- [x] Footer needs different organization of links and updated theming.
- [x] Index page needs finalized department text and theme mockup.
- [x] Make sure all pages have proper breadcrumbs.
- [x] Megamenus for academic/staff need updated text.
- [x] Search page needs updated theme and view organization.
- [x] Taxonomy pages need theming.
- [x] Theme needs finalized decision about header height.
- [x] Top bar department megamenu needs finalized link title and theming.

**Comment by dgallardo** [comment]
re: index page, ok to remove the gray bar completely

**Comment by dgallardo** [comment]
- [x] list of views from Desi

**Comment by dgallardo** [comment]
breadcrumbs will need to change...paths will need to change

**Comment by dgallardo** [comment]
re: theming for taxonomy page, see #356
- [ ] give honza title for taxonomy page
