### ISSUE TITLE
Things for Honza

### ISSUE THREAD

**Issue by dtruppi** [ucb-las/las-project#367]

**Comment by dtruppi** [comment]
- [x] Make "Maintenance" (http://test-lhrdredesign.pantheon.berkeley.edu/design/maintenance) unclickable

**Comment by dtruppi** [comment]
- [x] FAQs the same on all the Design Office pages; need to be sorted by topic

**Comment by dgallardo** [comment]
- [x] can user get a copy of their message when they submit something from the Contact form?
- [x] ~~fix links to the contact form so that the correct category is selected based on the contact form url (e.g. http://test-lhrdredesign.pantheon.berkeley.edu/contact/human-resources should link to the contact form with "Human Resources" already selected~~

**Comment by dgallardo** [comment]
- [x] ~~add spacing in between announcement type image and the text beside it (e.g. the gift symbol and "Site Updates/New Features"~~

**Comment by dgallardo** [comment]
- [x] ~~realign Reset button http://test-lhrdredesign.pantheon.berkeley.edu/resources~~

**Comment by dgallardo** [comment]
- [x] ~~fix menu bug: http://test-lhrdredesign.pantheon.berkeley.edu/facilities/building-coordination-for-main-library-gardner-stacks-and-moffitt~~

**Comment by dgallardo** [comment]
- [x] ~~do not show travel requests or expense reports in search results~~

**Comment by dgallardo** [comment]
- [x] see update to resources view in Requested Views tab -- add the text from the "Text" column of the requested views tab for the resources view

**Comment by dgallardo** [comment]
- [x] "Announcements section content is not that useful for Staff at this time. I would make it the bottom block on the right side until something of interest to staff is posted."
  Right side column on LAS index, rearrange block order: Popular Content, Contact, Announcements, Other News

**Comment by dgallardo** [comment]
- [x] general info search results not showing? http://test-lhrdredesign.pantheon.berkeley.edu/search?search=student&type=All&department=All&resource_type=All&page=1

**Comment by dgallardo** [comment]
- [x] "There are many Drupal linkchecker modules available. Definitely install and run before going live.  [I talked to Todd:  We use the Drupal 7 Link Checker module. -- please use the same one]"

**Comment by dgallardo** [comment]
- [x] in the supermenus for LHRD, is it possible to reorder the links so that they read down (in order) in the first column before jumping to the second column? Can this be done using CSS or should we just reorder them in the menu migrate?

**Comment by dgallardo** [comment]
- [x] add "Keys" to exposed filter for /forms view

**Comment by dgallardo** [comment]
- [x] "For staff contact information that’s displayed via a view consider pulling it in from the Staff Directory.  Ask Lynne Grigsby who you should contact in LAP for assistance with this."

**Comment by dgallardo** [comment]
- [x] "What part of the job posting is indexed, and searchable via the search box? Only the job title? If this is so, then the search box isn't necessary. The search box should search the full text of a job posting." -- make sure that search box searches, title and  body on pages:
- http://test-lhrdredesign.pantheon.berkeley.edu/lhrd/jobs/student-jobs, 
- http://test-lhrdredesign.pantheon.berkeley.edu/lhrd/jobs/academic-jobs
-  http://test-lhrdredesign.pantheon.berkeley.edu/lhrd/jobs/staff-jobs

**Comment by dgallardo** [comment]
- [x] "http://test-lhrdredesign.pantheon.berkeley.edu/lhrd/manuals/benefits-health-and-welfare/open-enrollment
  I think the content in the Resource column of the Resources for Open Enrollment view should be links."

**Comment by dgallardo** [comment]
- [x] "For the contact form consider using the Captcha module that’s used on the Library Website. Ask Lynne Grigsby who you should contact in LAP for assistance with this."

**Comment by dgallardo** [comment]
- [x] "If there aren't any open ...jobs, can you display text that informs the user that there aren't any jobs at this time? It would also be great if the search box didn't display when there aren't any jobs."  -- I've updated the unmigrainables with the text

**Comment by dgallardo** [comment]
- [x] move "No results" message from bottom of the page to underneath "0 items matched..." ex: http://test-lhrdredesign.pantheon.berkeley.edu/search?search=jobs&type=las_job&department=All

**Comment by dgallardo** [comment]
- [x] print layouts (see Print layouts tab in the unmigrainables)
