### ISSUE TITLE
Memory Issue: traveler cannot save an expense report because of memory usage

### ISSUE THREAD

**Issue by kcleonardo** [ucb-las/las-project#415]
update alert message to link to CSS form and submit to libtravel@lists.berkeley.edu. We can use wording from Local Recurrent Travel page: Please log these expenses on a CSS Domestic Travel Reimbursement Claim Form. For reference, please indicate the Travel Pre-approval Request number on this form. Instead of submitting the online Travel Expense Report in the LAS system, please submit this form and any required receipts to LBS via e-mail at libtravel@lists.berkeley.edu (link sends e-mail).

**Comment by dgallardo** [comment]
honza noted that he needed to fix travel reimb calculation scripts (no further description of issue given)

**Comment by kcleonardo** [comment]
add suggestion: If uploading multiple files, try combining files into a single file and upload that file.

**Comment by kcleonardo** [comment]
This will no longer be an issue when we start using the campus travel reimbursement system.
